<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>GBZEmuLibrary</RootNamespace>
    <AssemblyName>GBZEmuLibrary</AssemblyName>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Product>GBZEmuLibrary</Product>
    <Copyright>Copyright © 2017</Copyright>
    <ComVisible>false</ComVisible>
    <ApplicationIcon />
    <ApplicationManifest />
    <ApplicationId>9b7a7ace-f450-49cb-a219-dc02382d57d9</ApplicationId>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources/*.bin" />
  </ItemGroup>
</Project>