<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
        <PackageReference Include="xunit.v3" Version="3.2.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GBZEmuLibrary\GBZEmuLibrary.csproj" />
        <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
        <None Update="Fixtures\**\*" CopyToOutputDirectory="PreserveNewest" />

        <None Update="RomManifest.json" CopyToOutputDirectory="PreserveNewest" />
        <None Update="ExpectedRomIds.txt" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>